### ISSUE TITLE
Blokace přidání políček do menu

### ISSUE THREAD

**Issue by ununik** [oerdnj/woocommerce-zasilkovna#13]
Moc díky za skvělý plugin. Trošku jsem si s ním musel pohrát, protože mi nešlo zobrazit přidávání položek do menu. 

Způsobovala to funkce 'wc_get_chosen_shipping_method_ids', která pro mě v dannou chvíli neexistovala. Co mi pomohlo bylo přidání podmínky "if ( function_exists('wc_get_chosen_shipping_method_ids' ) )". 

Nezkoumal jsem to příliš do hloubky, ale patrně by to mohlo být vyřešeno tím, že by se ty všechny funkce, které nejsou v BE potřeba volali přes init až ve FE.

Ještě jednou moc díky

**Comment by ununik** [comment]
Nejsem uplne zbehly v githubu, tak nevim, co presne je potreba. 

Muj email je ununik@gmail.com, nevim, jestli je jeste neco dalsiho potreba.

Spise, nez nejaky dalsi vyvoj mam u sebe par zaplat (co jsem pochopil, tak to spis bylo jen z duvodu updatu coru WP),

**Comment by vyskoczilova** [comment]
Fixed in #19
