### ISSUE TITLE
pokud není nastavena cena dobírky pak error

### ISSUE THREAD

**Issue by mikethejet** [oerdnj/woocommerce-zasilkovna#9]
https://github.com/oerdnj/woocommerce-zasilkovna/blob/601403fa3ca062013649ab7499e4fd1f278eee85/zasilkovna.php#L154

[pid 21319] [client 94.138.124.124:1575] mod_fcgid: stderr: PHP Fatal error:  Call to a member function get_instance_option() on null in /var/www/clients/client3/web7/web/wp-content/plugins/woocommerce-zasilkovna-master/zasilkovna.php on line 154

![image](https://user-images.githubusercontent.com/2683571/49079078-01fd3400-f240-11e8-921d-db1c9f09ae96.png)

**Comment by vyskoczilova** [comment]
Fixed in #4
